### ISSUE TITLE
Globbing multiple files

### ISSUE THREAD

**Issue by rstacruz** [anarh/node-sass-import#9]
```scss
@import './components/*';
```

This works right now if it only matches one file. It should ideally return every .scss in there, concatenated (as `{ contents: '..' }`). Of course this approach means you can't intermix .scss and .sass, but hey, you probably shouldn't anyway.

**Comment by anarh** [comment]
Hey @rstacruz do you have a use case I can take a look at?

**Comment by rstacruz** [comment]
Yep! http://rscss.io

**Comment by anarh** [comment]
@rstacruz very nice work on rscss!!

**Comment by anarh** [comment]
Hey @rstacruz, 
So after trying a few scenarios, it appears the easier route might be using some entry file (index.scss) to import/list all the necessary files needed **vs.** going the glob (**/*) route. The reason behind this is because I'm using the resolve module to lookup files in both the npm & local filesystems. That resolve module unfortunately does not take raw globs for lookups for now. Adding that feature would require prior knowledge through the '@import url' as to whether the '@import url' (e.g. @import somecss/*) is referring to a local lookup or an npm(node_modules) lookup. I didn't want to add some form of symbols (e.g. ~) to indicate that it's an npm module because that approach is an anti-pattern approach. And because I wanted to stay true to the npm patterns (require), I offloaded the lookup to the "resolve" module to do the dirty work of figuring out the location of the '@imported' files regardless of where they may be located just like with javascript "require". 

Let me know if you have some thoughts or suggestions around getting your proposal to work while still maintaining the patterns. In most of my work, I always use an entry file that lists all the files individually. I also see most folks and libraries doing the same. But I do recognize the appeal to not having to list all the files by hand if you don't have to.

**Comment by rstacruz** [comment]
Hm, lemme think about it and try to hack around it.

**Comment by rstacruz** [comment]
I don't think there needs to be a special symbol or anything. All that needs in the module's logic is to do something different if it matches more than 1:

```js
// pseudo-code

files = glob('components/*')
if (files.length === 1) {
  return { file: files[0] } /* eg, 'components/button' */
} else {
  return { contents: '@import "components/button"; @import "components/form";' }
}
```

Looking at the code, this isn't so simple because you need to do [async.parallel](http://caolan.github.io/async/docs.html#.parallel) among the `resolver()` calls, so there's some internal API rearranging that needs to happen, but it's possible :)
